import type { CountrySummary } from '@/features/countries/models/country';

export const mockCountrySummaries: CountrySummary[] = [
  {
    code: 'DEU',
    name: 'Germany',
    population: 81770900,
    region: 'Europe',
    capital: 'Berlin',
    flagAlt: 'Flag of Germany',
    flagUrl: 'https://flagcdn.com/w320/de.png',
  },
  {
    code: 'USA',
    name: 'United States',
    population: 323947000,
    region: 'Americas',
    capital: 'Washington, D.C.',
    flagAlt: 'Flag of the United States',
    flagUrl: 'https://flagcdn.com/w320/us.png',
  },
  {
    code: 'BRA',
    name: 'Brazil',
    population: 206135893,
    region: 'Americas',
    capital: 'Brasilia',
    flagAlt: 'Flag of Brazil',
    flagUrl: 'https://flagcdn.com/w320/br.png',
  },
  {
    code: 'ISL',
    name: 'Iceland',
    population: 334300,
    region: 'Europe',
    capital: 'Reykjavik',
    flagAlt: 'Flag of Iceland',
    flagUrl: 'https://flagcdn.com/w320/is.png',
  },
  {
    code: 'JPN',
    name: 'Japan',
    population: 126960000,
    region: 'Asia',
    capital: 'Tokyo',
    flagAlt: 'Flag of Japan',
    flagUrl: 'https://flagcdn.com/w320/jp.png',
  },
  {
    code: 'NGA',
    name: 'Nigeria',
    population: 206139587,
    region: 'Africa',
    capital: 'Abuja',
    flagAlt: 'Flag of Nigeria',
    flagUrl: 'https://flagcdn.com/w320/ng.png',
  },
  {
    code: 'FRA',
    name: 'France',
    population: 66710000,
    region: 'Europe',
    capital: 'Paris',
    flagAlt: 'Flag of France',
    flagUrl: 'https://flagcdn.com/w320/fr.png',
  },
  {
    code: 'AUS',
    name: 'Australia',
    population: 24117360,
    region: 'Oceania',
    capital: 'Canberra',
    flagAlt: 'Flag of Australia',
    flagUrl: 'https://flagcdn.com/w320/au.png',
  },
];
